server:
  port: 80
spring:
  application:
    name: cloud-consul-order
  cloud:
    consul:
      host: 82.157.186.132
      port: 8500
      discovery:
        service-name: ${spring.application.name}